typography_spectrum: 0.942551756510511
color:
  brandStrength: 0.3352607460692525
  lightness: 0.8322198069654405
  saturation: 0.9170570976566523
  rhythmicContrast: 0.6985558166634291
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.5338754507247359
name: testfor rich
navigation:
  - name: Sea of Surrender
    id: 1e3e0803-1161-44ed-b2ad-2f9f443c40ac
    type: content
  - name: 'Books, apps, posts and more'
    url: 'http://www.thesunthemoonthestarsandmaya.com'
    type: external
  - name: Maya
    url: 'http://thegrid.ai/maya'
    type: external
title: Rich Okun
description: in words and pictures
