typography_spectrum: 0.8650587238371372
color:
  brandStrength: 0.3352607460692525
  lightness: 0.8322198069654405
  saturation: 0.9170570976566523
  rhythmicContrast: 0.6985558166634291
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.31430257204920053
analytics:
  google: UA-35516913-1
name: testfor rich
navigation:
  - name: Vignettes
    url: 'http://thegrid.ai/richokun'
    type: external
  - name: Stone Carvings
    url: 'https://thegrid.ai/homepage1/'
    type: external
  - name: Maya - App and Bedtime Stories
    url: 'https://thegrid.ai/maya-books-apps-and-more/'
    type: external
  - name: Published Books
    url: 'http://www.amazon.com/Rich-Okun/e/B00DZO54IG/'
    type: external
  - name: Buy Prints
    url: 'http://fineartamerica.com/profiles/richard-okun.html'
    type: external
  - name: Interviews and more
    url: 'https://thegrid.ai/author-interviews/'
    type: external
  - name: Book videos
    url: 'https://thegrid.ai/test1site/'
    type: external
  - name: Maya Posts
    url: 'https://thegrid.ai/maya/'
    type: external
title: Rich Okun
description: in words and pictures
